### ISSUE TITLE
BUG Wrong Flow Data???

### ISSUE THREAD

**Issue by nilbest** [hafidhh/FlowSensor-Arduino#12]
**Describe the bug**
I think there is a significant error somewhere in the Code. 
But only to how to read the flow Data. I tested today the code with a 10L bucket. With a contestant flow in the bucked.
But the Flow Rate dropped significantly. My stopped time was around 54secs for the 10L bucked to fill up. 
The Result shown on the serial Screen told me by using getFlowRate_s a Number constant lower than 0.00 and the number for l/min was also never peaking over 1.11. 
The Flowrate was constantly dropping, witches seems auspices to me. (Because I only opened the valve in one go and I also closed it in one go) 
However, the measurement of the Amount was quite accurate. 

**To Reproduce**
Measure the FlowRate with a 10L Bucked and stop the time how long it will take to fill up.
Check the Time it took and how much it filled up and compare that with the Data the program Tells you...
Recalculate the flow rate with your measured Time and the amount the bucked is filled. Now you get your average flow Rate. 

PicturesOf the Test Setup:
![Setup_1](https://github.com/hafidhh/FlowSensor-Arduino/assets/104395997/5c630785-66c4-4d00-b2ab-99f915f57ca3)
![Setup_2](https://github.com/hafidhh/FlowSensor-Arduino/assets/104395997/aa551b83-c883-4128-b1df-82cdb3d36119)

Pictures of what I measured:
![Filled_Bucked_after_Time](https://github.com/hafidhh/FlowSensor-Arduino/assets/104395997/162116ba-b4a1-444f-b62d-5b300008ebce)

![Stopped_Time](https://github.com/hafidhh/FlowSensor-Arduino/assets/104395997/8b518f3c-5f9a-4a33-be67-5442c27af3b5)

What I calculated:
![What_I_calcilated](https://github.com/hafidhh/FlowSensor-Arduino/assets/104395997/22eb3e7a-5859-4028-99d9-c86908ae0ed0)

**Expected behavior**
To get some Flowrate near my calculations...

**Screenshots**
My main.cpp void loop() Code I used for the fast test
![Simple_Test_Code](https://github.com/hafidhh/FlowSensor-Arduino/assets/104395997/ecf577b1-af1f-4d88-9a5c-188e8ce74676)

How the test started:
![Screenshot_Start](https://github.com/hafidhh/FlowSensor-Arduino/assets/104395997/b1693602-c86f-4c7f-a052-e5827db1b238)

How the Test ended:
![Screenshot_End](https://github.com/hafidhh/FlowSensor-Arduino/assets/104395997/b6add0ca-ce39-4f2f-8ff2-4cfd35a078c5)

**IDE and its version:**
 - Arduino (2.1.0)
 - PlatformIO (3.4.4)

**Device**
 - Arduino Uno
 - YF-S201 FlowSensor

**Comment by hafidhh** [comment]
thanks for reporting the bug and thanks for the pull request to fix it.

**Comment by hjmhardsoft** [comment]
> **Describe the bug**
> I think there is a significant error somewhere in the Code. 
> But only to how to read the flow Data. I tested today the code with a 10L bucket. With a contestant flow in the bucked.
> But the Flow Rate dropped significantly. My stopped time was around 54secs for the 10L bucked to fill up. 
> The Result shown on the serial Screen told me by using getFlowRate_s a Number constant lower than 0.00 and the number for l/min was also never peaking over 1.11. 
> The Flowrate was constantly dropping, witches seems auspices to me. (Because I only opened the valve in one go and I also closed it in one go) 
> However, the measurement of the Amount was quite accurate. 
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> Measure the FlowRate with a 10L Bucked and stop the time how long it will take to fill up.
> Check the Time it took and how much it filled up and compare that with the Data the program Tells you...
> Recalculate the flow rate with your measured Time and the amount the bucked is filled. Now you get your average flow Rate. 
> 
> PicturesOf the Test Setup:
> ![Setup_1](https://github.com/hafidhh/FlowSensor-Arduino/assets/104395997/5c630785-66c4-4d00-b2ab-99f915f57ca3)
> ![Setup_2](https://github.com/hafidhh/FlowSensor-Arduino/assets/104395997/aa551b83-c883-4128-b1df-82cdb3d36119)
> 
> Pictures of what I measured:
> ![Filled_Bucked_after_Time](https://github.com/hafidhh/FlowSensor-Arduino/assets/104395997/162116ba-b4a1-444f-b62d-5b300008ebce)
> 
> ![Stopped_Time](https://github.com/hafidhh/FlowSensor-Arduino/assets/104395997/8b518f3c-5f9a-4a33-be67-5442c27af3b5)
> 
> 
> What I calculated:
> ![What_I_calcilated](https://github.com/hafidhh/FlowSensor-Arduino/assets/104395997/22eb3e7a-5859-4028-99d9-c86908ae0ed0)
> 
> 
> **Expected behavior**
> To get some Flowrate near my calculations...
> 
> 
> 
> **Screenshots**
> My main.cpp void loop() Code I used for the fast test
> ![Simple_Test_Code](https://github.com/hafidhh/FlowSensor-Arduino/assets/104395997/ecf577b1-af1f-4d88-9a5c-188e8ce74676)
> 
> How the test started:
> ![Screenshot_Start](https://github.com/hafidhh/FlowSensor-Arduino/assets/104395997/b1693602-c86f-4c7f-a052-e5827db1b238)
> 
> How the Test ended:
> ![Screenshot_End](https://github.com/hafidhh/FlowSensor-Arduino/assets/104395997/b6add0ca-ce39-4f2f-8ff2-4cfd35a078c5)
> 
> **IDE and its version:**
>  - Arduino (2.1.0)
>  - PlatformIO (3.4.4)
> 
> **Device**
>  - Arduino Uno
>  - YF-S201 FlowSensor
> 

I was experiencing the same issue. Thanks by reporting so detailed and thanks to who solve the issue.
I will recompile and check behavior.
