### ISSUE TITLE
BUG Doesn't compile

### ISSUE THREAD

**Issue by rosenhauer** [hafidhh/FlowSensor-Arduino#23]
In line 54 of the cpp there is:

void FlowSensor::begin(void (*userFunc)(void), bool pullup = false)

this does not match the header file (line 38):
void begin(void (*userFunc)(void));

The header file needs to be updated to :
(38) --> void begin(void (*userFunc)(void), bool pullup = false);
and the cpp file 
(54) --> void FlowSensor::begin(void (*userFunc)(void), bool pullup)

For proper use of the default value.

**Comment by hafidhh** [comment]
i have fix it on v1.5.0. thank for reporting this issue
