### ISSUE TITLE
Implement DigitalRead in place of Interrupt

### ISSUE THREAD

**Issue by abdazz25** [hafidhh/FlowSensor-Arduino#6]
Hi guys,
Thanks for this Library, it's going to help a lot of us.
I have been struggling to have a proper working flow sensor program.
Most of the programs I have come across use attachInterrupt to get the flow sensor readings, however, I have not been able to use this specifically on Arduino Nano (I am using Pin 8), the work around to get the Flow Sensor reading is to use digitalRead.

Would it be worth it to have this implemented just to have the library have more flexibility.

Thanks and regards,
Abdalla

**Comment by hafidhh** [comment]
You must use interrupt pins, not all pins can be used for interrupt, for Arduino nano use pins 2 and 3 for interrupt.

https://www.arduino.cc/reference/en/language/functions/external-interrupts/attachinterrupt/

Thanks

**Comment by abdazz25** [comment]
Thank you hafidh.
I will test that up.
