### ISSUE TITLE
Reset Pulse to 0

### ISSUE THREAD

**Issue by Schlappo22** [hafidhh/FlowSensor-Arduino#9]
Hello,

I am working on a project where I dispense a certain amount of liquid on a press of a button. The pump will pump as long as the flow meter has not reached the desired value. I got everything to work. But when I try to run again (unless I restart the Arduino), I am already above the value as the pulses are not reset.

I didn't find a function in the library and was wondering if that is something that we could implement?
Or am I missing something?

Regards

**Comment by Schlappo22** [comment]
I added this into the library, call Sensor.reset() to restart.

`/**
 * @brief reset pulse
 * 
 */
void FlowSensor::reset()
{
  this->_pulse=0;
  this->_totalpulse=0;
  this->_volume=0;
}`

**Comment by hafidhh** [comment]
Hello,

I've added the resetVolume function in the latest update

Thank you
